In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7])

In [19]:
# #we can define the datatype too but use it only with the list
# a = np.array([2,,3,4,np.NAN,5,6],dtype=np.float32)
# a
a = np.arange(1,10)
matrix = a.reshape(3,3)
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matrix.mean()

5.0

In [22]:
#manual matrix
m1 = np.array([[2,3,4],[5,6,7],[8,9,10]])
np.add(matrix,m1)

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [23]:
np.eye(3,3)#creates identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.zeros([3,4])
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
#to save the data to a file ('file_name','data')
np.save('jk.npy',matrix)
#to read the data from the file
sav = np.load('jk.npy')
sav

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#numpy broadcasting?
#to multiply matrix of different dimensions and show null values if theres no val present
x = np.empty_like(matrix)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matrix[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [44]:
a = np.arange(1,10)
x = a.reshape(3,3)
x
a.shape

(9,)

In [40]:
x[1:3,1:2]

array([[5],
       [8]])

In [42]:
a.shape()

TypeError: 'tuple' object is not callable

In [ ]:
#too many indices = data is in 1d and u want to acess the data in 2d

In [51]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
new  = a[1:3,1:3]
new

array([[5, 6],
       [8, 9]])

In [49]:
new[1,1] = 99
new

array([[ 5,  6],
       [ 8, 99]])

In [50]:
a
#new is the instance of a any change in

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])